name: Deploy to Production

on:
  push:
    branches: [production]

jobs:
  redeploy_everything:
    name: Redeploying everything
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST_IP }}
          username: navya
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/payFlow
            git checkout production || git checkout -b production origin/production
            git pull origin production

            export PATH="/home/navya/.nvm/versions/node/v22.19.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

            npm install


            echo "Restarting services..."
            JWT_SECRET=${{ secrets.JWT_SECRET }} pm2 restart frontend --update-env
            JWT_SECRET=${{ secrets.JWT_SECRET }} pm2 restart backend --update-env

            echo "Deployment completed successfully!"
